### ISSUE TITLE
npm install and npm run dev not working

### ISSUE THREAD

**Issue by katopz** [developit/preact-todomvc#9]
**Step to reproduce**
1. Checkout fresh install.
1. `npm i`
1. `npm run dev`

**Results**
- webpack throw error

**Workaround**
1. `yarn install` // To install dependency
1. `npm run build` // To create build folder
1. `npm run dev` // To start webpack-dev-server 

**Or**
1. `yarn install` // To install dependency
1. `npm run start`  // To create build folder and start http-server

PS : I can see some movement in other branch so I didn't propose fixed PR to prevent conflict. :)

**Comment by jkukul** [comment]
FWIW, When running `npm run dev` I am getting the following stack-trace:

```
ERROR in ./src/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/jakub/repos/developit/preact-todomvc/node_modules/babel-preset-es2015/lib/index.js
    at createDescriptor (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/jakub/repos/developit/preact-todomvc/node_modules/@babel/core/lib/config/partial.js:85:55)
```
